### PR TITLE
Make sort function for channelSelect optional

### PR DESCRIPTION
**Pull request by DJKnaeckebrot**

### CODE REVIEW

**Comment by DJKnaeckebrot** [comment]
I added a parameter to the channelSelect function to opt in/out the alphabetical order that was enabled by default.

**Review by zVapor-Dev — APPROVED** [review]
If this is tested and it works I'm fine with it

**Review by iMidnights — APPROVED** [review]
Looks good!

**Review by PlainDevelopment — APPROVED** [review]
i agree good sir

**Comment by DJKnaeckebrot** [comment]
> If this is tested and it works I'm fine with it

Tested with true false values and not passing the param. All works fine

**Pull request closed without merging**
