### PR TITLE
Fixed category handler

### PR DESCRIPTION
**Pull request by iMidnights**

### CODE REVIEW

**Comment by iMidnights** [comment]
> @iMidnights Ping me 2 times a day starting on Sunday, please. I don't have time to publish it to NPM atm.

Only if I don't forget 🤣

**Comment by breftejk** [comment]
My working hours start on Monday, but maybe I can make it on Sunday haha

No worries, if we both forget, the person who's requested this feature will remind us 😆

**Comment by breftejk** [comment]
I'm so focused on v3 right now I probably will forget about this v2 feature. Lemme set a reminder in my calendar xd

**Comment by DJKnaeckebrot** [comment]
This is microsoft support how can i help you? Why am i set to review? xd lemme spin up my dev and add categorySet. @iMidnights will it also work with multiRow?

**Comment by iMidnights** [comment]
> @iMidnights will it also work with multiRow?

me has no idea

**Comment by DJKnaeckebrot** [comment]
time to find out i guess lol

**Comment by breftejk** [comment]
> This is microsoft support how can i help you? Why am i set to review? xd 

Because me cba xd

**Comment by iMidnights** [comment]
> @DJKnaeckebrot could u pls create a new soft ui release me cba

**Comment by breftejk** [comment]
We are all lazy bitches. But we're on our week off, I - as an CEO and the Founder - forgive us all.

**Comment by DJKnaeckebrot** [comment]
> > @DJKnaeckebrot could u pls create a new soft ui release me cba
> 
> 
> 
> 

What should be in it? Or did you already pushed?

**Comment by iMidnights** [comment]
> Rest assured, you can continue to cba to do anything

I wanna sleep but I don't have the superpower to go to sleep during the day

**Comment by iMidnights** [comment]
> > > @DJKnaeckebrot could u pls create a new soft ui release me cba
> 
> What should be in it? Or did you already pushed?

already pushed

**Comment by iMidnights** [comment]
> > > > > @DJKnaeckebrot could u pls create a new soft ui release me cba
> > > 
> > > 
> > > What should be in it? Or did you already pushed?
> > 
> > 
> > already pushed
> 
> Sure will release it and update the changelog

we need to somehow make it dynamic

**Pull request closed without merging**
